Recipe.create!([
  {title: "Cookies", chef: "Cookie Monster", ingredients: "cookie mix, egg, milk", directions: "pour mix in bowl, add egg and milk, mix, cook", image_url: "http://cdn.grindtv.com/wp-content/uploads/2013/09/cookiemonster.jpeg", prep_time: 35},
  {title: "lagsana", chef: "Bad Josh", ingredients: "socks, toothpaste, butterscotch", directions: "add butterscotch to sock, add toothpaste to mixture, heat at 325 for 16 hours, put out fire", image_url: "http://www.lesauce.com/wp-content/uploads/2013/01/tumblr_m2t8mqROz21qcs8rio1_500.gif", prep_time: 450},
  {title: "Hand Sandwich", chef: "Not so bad Josh", ingredients: "left hand, right hand, cheese slice product", directions: "take wrapper off cheese slice product, place cheese product in left hand, put your hands together", image_url: "https://5f7mk98d5d69eqvo-zippykid.netdna-ssl.com/wp-content/uploads/2012/06/Hand-Sandwiches.jpeg", prep_time: 3},
  {title: "Cake", chef: "Sweedish Chef", ingredients: "egg, flour, milk, salt, shortening, baking soda, sugar, vanilla", directions: "mix ingredients together in a bowl, stir well, give up, call a professional baker", image_url: "http://i192.photobucket.com/albums/z167/Great_WhiteSnark/R2-D2_Cake_Fail.jpg", prep_time: 30},
  {title: "Junk food", chef: "The Swedish Chef", ingredients: "candy bar from vending machine", directions: "unwrap, enjoy", image_url: "http://vignette1.wikia.nocookie.net/bioshock/images/f/fe/Candy_Bar_Render_BSi.png/revision/latest?cb=20150502220128", prep_time: 65},
  {title: "egg", chef: "Steve", ingredients: "live chicken, pair of gloves", directions: "hold chicken firmly and squeeze", image_url: "https://timedotcom.files.wordpress.com/2019/01/gettyimages-914246230.jpg?quality=85", prep_time: 2},
  {title: "tumms", chef: "pharmacist", ingredients: "tumms", directions: "eat it", image_url: "https://cdn.influenster.com/media/product/image/carousel-image1.png.750x750_q85ss0_progressive.png", prep_time: 1},
  {title: "Egg", chef: "Chicken", ingredients: "Chicken", directions: "squeeze", image_url: "https://opimedia.azureedge.net/-/media/Images/MEN/Editorial/Blogs/Homesteading-and-Livestock/5-Clever-Chicken-Egg-Incubation-Tips/Chick-Inside-An-Egg-jpg.jpg?h=374&w=550&la=en&hash=41100CC9F7FE704C600FCFBE67048C8D50CE9919", prep_time: 1}
])
